--Biobase
minetest.register_alias("dirt_cold_grass", "ebiomes:dirt_with_grass_cold")
minetest.register_alias("dirt_with_cold_grass_footsteps", "ebiomes:dirt_with_grass_cold_footsteps")
minetest.register_alias("dirt_with_med_grass", "ebiomes:dirt_with_grass_med")
minetest.register_alias("dirt_with_med_grass_footsteps", "ebiomes:dirt_with_grass_med_footsteps")
minetest.register_alias("dirt_with_steppe_grass", "ebiomes:dirt_with_grass_steppe")
minetest.register_alias("dirt_with_steppe_grass_footsteps", "ebiomes:dirt_with_grass_steppe_footsteps")
minetest.register_alias("dirt_with_warm_steppe_grass", "ebiomes:dirt_with_grass_steppe_warm")
minetest.register_alias("dirt_with_warm_steppe_grass_footsteps", "ebiomes:dirt_with_grass_steppe_warm_footsteps")
minetest.register_alias("dirt_with_cold_steppe_grass", "ebiomes:dirt_with_grass_steppe_cold")
minetest.register_alias("dirt_with_cold_steppe_grass_footsteps", "ebiomes:dirt_with_grass_steppe_cold_footsteps")
minetest.register_alias("dirt_with_swamp_grass", "ebiomes:dirt_with_grass_swamp")
minetest.register_alias("dirt_with_swamp_grass_footsteps", "ebiomes:dirt_with_grass_swamp_footsteps")
minetest.register_alias("swamp_water", "ebiomes:swamp_water_source")
minetest.register_alias("dirt_with_warm_grass", "ebiomes:dirt_with_grass_warm")
minetest.register_alias("dirt_with_warm_grass_footsteps", "ebiomes:dirt_with_grass_warm_footsteps")
minetest.register_alias("dry_dirt_with_grass", "ebiomes:dry_dirt_with_grass_arid")
minetest.register_alias("dry_dirt_with_grass_footsteps", "ebiomes:dry_dirt_with_grass_arid_footsteps")
minetest.register_alias("cool_dry_dirt_with_grass", "ebiomes:dry_dirt_with_grass_arid_cool")
minetest.register_alias("cool_dry_dirt_with_grass_footsteps", "ebiomes:dry_dirt_with_grass_arid_cool_footsteps")
minetest.register_alias("wet_peat_with_green_swamp_moss", "ebiomes:peat_wet_with_swamp_moss_green")
minetest.register_alias("wet_peat_with_green_swamp_moss_footsteps", "ebiomes:peat_wet_with_swamp_moss_green_footsteps")
minetest.register_alias("peat_with_yellow_swamp_moss", "ebiomes:peat_with_swamp_moss_yellow")
minetest.register_alias("peat_with_yellow_swamp_moss_footsteps", "ebiomes:peat_with_swamp_moss_yellow_footsteps")

minetest.register_alias("reeds", "ebiomes:reeds")
minetest.register_alias("green_marsh_grass", "ebiomes:marsh_grass_green")
minetest.register_alias("yellow_marsh_grass", "ebiomes:marsh_grass_yellow")


--Decors
minetest.register_alias("warm_bush_stem", "ebiomes:bush_stem_warm")
minetest.register_alias("warm_bush_leaves", "ebiomes:bush_leaves_warm")
minetest.register_alias("warm_bush_sapling", "ebiomes:bush_sapling_warm")
minetest.register_alias("hardy_bush_stem", "ebiomes:hardy_bush_stem")
minetest.register_alias("hardy_bush_leaves", "ebiomes:hardy_bush_leaves")
minetest.register_alias("hardy_bush_sapling", "ebiomes:hardy_bush_sapling")
minetest.register_alias("thorn_bush_leaves", "ebiomes:thorn_bush_leaves")
minetest.register_alias("thorn_bush_sapling", "ebiomes:thorn_bush_sapling")

minetest.register_alias("peashrub_peas", "ebiomes:peashrub_peas")
minetest.register_alias("cooked_peas", "ebiomes:peas_cooked")
minetest.register_alias("bucket_with_peas", "ebiomes:bucket_peas")
minetest.register_alias("cooked_peas", "ebiomes:peas_cooked")
minetest.register_alias("peashrub_leaves_with_peas", "ebiomes:peashrub_leaves_with_peas")
minetest.register_alias("peashrub_stem", "ebiomes:peashrub_stem")
minetest.register_alias("peashrub_leaves", "ebiomes:peashrub_leaves")
minetest.register_alias("peashrub_sapling", "ebiomes:peashrub_sapling")

minetest.register_alias("blackcurrant_bush_leaves", "ebiomes:blackcurrant_bush_leaves")
minetest.register_alias("blackcurrant_bush_leaves", "ebiomes:blackcurrant_bush_leaves_with_berries")
minetest.register_alias("blackcurrant_bush_sapling", "ebiomes:blackcurrant_bush_sapling")
minetest.register_alias("blackcurrants", "ebiomes:blackcurrants")
minetest.register_alias("redcurrant_bush_leaves", "ebiomes:redcurrant_bush_leaves")
minetest.register_alias("redcurrant_bush_leaves", "ebiomes:redcurrant_bush_leaves_with_berries")
minetest.register_alias("redcurrant_bush_sapling", "ebiomes:redcurrant_bush_sapling")
minetest.register_alias("redcurrants", "ebiomes:redcurrants")
minetest.register_alias("gooseberry_bush_leaves", "ebiomes:gooseberry_bush_leaves")
minetest.register_alias("gooseberry_bush_leaves", "ebiomes:gooseberry_bush_leaves_with_berries")
minetest.register_alias("gooseberry_bush_sapling", "ebiomes:gooseberry_bush_sapling")
minetest.register_alias("gooseberries", "ebiomes:gooseberries")
minetest.register_alias("cowberry_bush_leaves", "ebiomes:cowberry_bush_leaves")
minetest.register_alias("cowberry_bush_leaves", "ebiomes:cowberry_bush_leaves_with_berries")
minetest.register_alias("cowberry_bush_sapling", "ebiomes:cowberry_bush_sapling")
minetest.register_alias("cowberries", "ebiomes:cowberries")

minetest.register_alias("cranberry_patch", "ebiomes:cranberry_patch")
minetest.register_alias("cranberries", "ebiomes:cranberries")
minetest.register_alias("sundew", "ebiomes:sundew")
minetest.register_alias("marigold", "ebiomes:marigold")
minetest.register_alias("marsh_stitchwort", "ebiomes:marsh_stitchwort")
minetest.register_alias("black_iris", "ebiomes:black_iris")
minetest.register_alias("cladanthus", "ebiomes:cladanthus")
minetest.register_alias("savory", "ebiomes:savory")
minetest.register_alias("staehelina", "ebiomes:staehelina")
minetest.register_alias("larkspur", "ebiomes:larkspur")
minetest.register_alias("persian_buttercup", "ebiomes:buttercup_persian")
minetest.register_alias("yellow_chrysanthemum", "ebiomes:chrysanthemum_yellow")
minetest.register_alias("blue_allium", "ebiomes:blue_allium")
minetest.register_alias("purple_blue_allium", "ebiomes:blue_allium_purple")
minetest.register_alias("altai_tulip", "ebiomes:altai_tulip")
minetest.register_alias("russian_iris", "ebiomes:russian_iris")
minetest.register_alias("siberian_lily", "ebiomes:siberian_lily")
minetest.register_alias("mountain_lily", "ebiomes:mountain_lily")

--Woods

minetest.register_alias("alder_tree", "ebiomes:alder_tree")
minetest.register_alias("alder_wood", "ebiomes:alder_wood")
minetest.register_alias("alder_leaves", "ebiomes:alder_leaves")
minetest.register_alias("alder_sapling", "ebiomes:alder_sapling")
minetest.register_alias("ash_tree", "ebiomes:ash_tree")
minetest.register_alias("ash_wood", "ebiomes:ash_wood")
minetest.register_alias("ash_leaves", "ebiomes:ash_leaves")
minetest.register_alias("ash_sapling", "ebiomes:ash_sapling")
minetest.register_alias("birch_tree", "ebiomes:birch_tree")
minetest.register_alias("birch_wood", "ebiomes:birch_wood")
minetest.register_alias("birch_leaves", "ebiomes:birch_leaves")
minetest.register_alias("birch_sapling", "ebiomes:birch_sapling")
minetest.register_alias("chestnut_tree", "ebiomes:chestnut_tree")
minetest.register_alias("chestnut_wood", "ebiomes:chestnut_wood")
minetest.register_alias("chestnut_leaves", "ebiomes:chestnut_leaves")
minetest.register_alias("chestnut_sapling", "ebiomes:chestnut_sapling")
minetest.register_alias("chestnuts", "ebiomes:chestnuts")
minetest.register_alias("chestnuts_peeled", "ebiomes:chestnuts_peeled")
minetest.register_alias("chestnuts_roasted", "ebiomes:chestnuts_roasted")
minetest.register_alias("cypress_tree", "ebiomes:cypress_tree")
minetest.register_alias("cypress_wood", "ebiomes:cypress_wood")
minetest.register_alias("cypress_leaves", "ebiomes:cypress_leaves")
minetest.register_alias("cypress_sapling", "ebiomes:cypress_sapling")
minetest.register_alias("downy_birch_tree", "ebiomes:downy_birch_tree")
minetest.register_alias("downy_birch_wood", "ebiomes:downy_birch_wood")
minetest.register_alias("downy_birch_leaves", "ebiomes:downy_birch_leaves")
minetest.register_alias("downy_birch_sapling", "ebiomes:downy_birch_sapling")
minetest.register_alias("olive_tree", "ebiomes:olive_tree")
minetest.register_alias("olive_wood", "ebiomes:olive_wood")
minetest.register_alias("olive_leaves", "ebiomes:olive_leaves")
minetest.register_alias("olive_sapling", "ebiomes:olive_sapling")
minetest.register_alias("olives", "ebiomes:olives")
minetest.register_alias("pear_tree", "ebiomes:pear_tree")
minetest.register_alias("pear_wood", "ebiomes:pear_wood")
minetest.register_alias("pear_leaves", "ebiomes:pear_leaves")
minetest.register_alias("pear_sapling", "ebiomes:pear_sapling")
minetest.register_alias("pear", "ebiomes:pear")
minetest.register_alias("quince_tree", "ebiomes:quince_tree")
minetest.register_alias("quince_wood", "ebiomes:quince_wood")
minetest.register_alias("quince_leaves", "ebiomes:quince_leaves")
minetest.register_alias("quince_sapling", "ebiomes:quince_sapling")
minetest.register_alias("quince", "ebiomes:quince")
minetest.register_alias("dried_quince_pieces", "ebiomes:dried_quince_pieces")
minetest.register_alias("willow_tree", "ebiomes:willow_tree")
minetest.register_alias("willow_wood", "ebiomes:willow_wood")
minetest.register_alias("willow_leaves", "ebiomes:willow_leaves")
minetest.register_alias("willow_sapling", "ebiomes:willow_sapling")











